spin_version = "1"
name = "finicky-whiskers"
version = "1.0.0"
trigger = { type = "http", base = "/" }

# Serve static files
[[component]]
id = "fileserver"
source = "components/fileserver.wasm"
files = [{ source = "site", destination = "/" }]
[component.trigger]
route = "/..."

# Redirect / to /index.html
[[component]]
id = "redirect-to-index"
source = "components/redirect.wasm"
environment = { DESTINATION = "/index.html" }
[component.trigger]
route = "/"
executor = { type = "wagi" }

# Tally an individual event
[[component]]
id = "tally"
source = "components/tally.wasm"
environment = {REDIS_ADDRESS = "redis://localhost:6379/", REDIS_CHANNEL = "fw-tally"}
[component.trigger]
route = "/tally"

# Initialize session data
[[component]]
id = "session"
source = "session/ruby.wasm"
files = [
  { source = "session/lib", destination = "/lib" },
  { source = "session/.gem", destination = "/.gem" },
  { source = "session/ruby/usr", destination = "/usr" },
]
[component.trigger]
executor = { type = "wagi", argv = "${SCRIPT_NAME} -v /lib/session.rb ${SCRIPT_NAME} ${ARGS}" }
route = "/session"
[component.environment]
HOME = "/"
GEM_HOME = "/.gem"

# Get the scores for a particular game
[[component]]
id = "scoreboard"
source = "components/scoreboard.wasm"
environment = {REDIS_ADDRESS = "redis://localhost:6379/"}
[component.trigger]
route = "/score"
